// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdjawutgjclduujfkest.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkamF3dXRnamNsZHV1amZrZXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDAwNjQsImV4cCI6MjA2ODk3NjA2NH0.0FCWRZHge-SWCDi92qLa1E4nmWESBu2OWNIbgYTdIjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});